### ISSUE TITLE
Question: could DataToolkit.jl handle data versioning?

### ISSUE THREAD

**Issue by camilogarciabotero** [tecosaur/DataToolkit.jl#4]
Hi,

Thanks for working on this package. I was wondering if there is any already implemented feature in the `Data.toml` to handle versioning of the data. I was thinking something similar as in [`dolt`](https://github.com/dolthub/dolt) or as in the [`DataSets.jl`](https://github.com/JuliaComputing/DataSets.jl).

Best

**Comment by tecosaur** [comment]
Versioning is supported via the `versions` plugin and duplication. For example,

### Data.toml

```toml
data_config_version = 0
plugins = ["versions"]

[[thing]]
version = 1

    [[thing.storage]]
    driver = "raw"
    value = "a"

    [[thing.loader]]
    driver = "passthrough"

[[thing]]
version = 2

    [[thing.storage]]
    driver = "raw"
    value = "b"

    [[thing.loader]]
    driver = "passthrough"
```

### Julia REPL

```julia
julia> using DataToolkit
[ Info: Data set 'thing' had no UUID, one has been generated.
[ Info: Data set 'thing' had no UUID, one has been generated.

(demo) data> plugin add versions
 + Added plugins: versions

julia> d"thing"
ERROR: AmbiguousIdentifier: "thing" matches multiple data sets
    □:thing@1 [7eba51e8-1a88-4e64-8791-fa7b20a39fc5]
    □:thing@2 [ef154d2c-26ee-43bc-a5d2-faa32e1da9cf]
  [...]

julia> d"thing@1"
"a"

julia> d"thing@2"
"b"
```
