### ISSUE TITLE
Defining transformers in package extensions

### ISSUE THREAD

**Issue by Klafyvel** [tecosaur/DataToolkit.jl#60]
Hi! I just got stuck in my exploration of DataToolkit.jl (using the dev version). I'm trying to define a DataLoader for RSS feeds in an extension of a package (the rationale being that this loader should not be in DataToolkitCommon as it is quite specific). I'm doing something like:

<details>

```julia
module DataToolkitExt

using RSSFeeds
using Tables
using DataToolkitCore

function DataToolkitCore.load(loader::DataLoader{:rss}, from::IO, sink::Type)
    return invokelatest(Base.parse, RSSFeeds.RSS, take!(from)) |>
        if sink == Any || QualifiedType(sink) == QualifiedType(:RSSFeeds, :RSS)
        identity
    elseif sink == Matrix
        Tables.matrix
    else
        sink
    end
end

DataToolkitCore.supportedtypes(::Type{DataToolkitCore.DataLoader{:rss}}) = [
    QualifiedType(:DataFrames, :DataFrame),
    QualifiedType(:RSSFeeds, :RSS),
    QualifiedType(:Base, :Matrix),
]

function lint(loader::DataLoader{:rss}, ::Val{:no_rss_config})
    return if haskey(loader.parameters, "args")
        LintItem(
            loader, :warning, :no_rss_config,
            "RSS loader does not accept any customization yet.",
            nothing, false
        )
    end
end

end
```

</details>

And then I created a test `Data.toml` like:
<details>

```toml
data_config_version = 0
uuid = "6cdfde7c-63e8-43bb-bebe-7e17fc6a7fa0"
name = "test"
plugins = []

[[bouletcorp]]
uuid = "db65c7c5-ac17-4566-a55c-a5e2f7d90e44"
    [[bouletcorp.storage]]
    driver = "filesystem"
    value = "bouletcorp.xml"
    [[bouletcorp.loader]]
    driver = "rss"
    type = "DataFrame"
```

</details>

However, it seems that `DataToolkitCore.jl` is not fully aware of the loader when I try to play with it:

```julia-repl
julia> dataset("bouletcorp")
DataSet test:bouletcorp
  Storage: filesystem(IO, Vector{UInt8}, String, FilePath, DirPath)
  Loaders: rss(DataFrame)

julia> read(dataset("bouletcorp"))
ERROR: UnsatisfyableTransformer: There are no transformers for "bouletcorp" that can provide a DataFrames.DataFrame.
 The defined transformers are as follows:
   DataLoader{rss}(DataFrame) -> []
```

Could it be that an `invokelatest` call may be missing in the Core somewhere?
