### ISSUE TITLE
tutorial error: stacktrace method not found

### ISSUE THREAD

**Issue by ggebbie** [tecosaur/DataToolkit.jl#61]
Great looking package with great documentation that fills an important gap. Thanks tecosaur!

Trying out DataToolkit for the first time and trying out the tutorial. I get the following error at the `init` stage. I have only spent 10 minutes and this may be user error.  Julia 1.11.5.

```julia
julia> using DataToolkit

(⋅) data> init
 Create Data.toml for current project? [Y/n]: y
 Name: datatoolkit_tutorial
 Use checksums by default? [Y/n]: n
 ✓ Created new data collection 'datatoolkit_tutorial' at /home/gebbie/scratch/datatoolkit_tutorial/Data.toml

SYSTEM (REPL): showing an error caused an error
ERROR:
MethodError: no method matching stacktrace(::MethodError)
The function `stacktrace` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  stacktrace(::Bool)
   @ Base stacktraces.jl:174
  stacktrace()
   @ Base stacktraces.jl:174
  stacktrace(::Vector{<:Union{Ptr{Nothing}, Base.InterpreterIP, Core.Compiler.InterpreterIP}}, ::Bool)
   @ Base stacktraces.jl:161
  ...

Stacktrace:
  [1] scrub_repl_backtrace(bt::MethodError)
    @ Base ./client.jl:101
  [2] print_response(errio::IO, response::Any, backend::Union{…}, show_value::Bool, have_color::Bool, specialdisplay::Union{…}
)
    @ REPL ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:429
  [3] (::REPL.var"#70#71"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:405
  [4] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:678
  [5] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:403
  [6] (::REPL.var"#do_respond#100"{…})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1035
  [7] #invokelatest#2
    @ ./essentials.jl:1055 [inlined]
  [8] invokelatest
    @ ./essentials.jl:1052 [inlined]
  [9] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2755
 [10] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1506
 [11] (::REPL.var"#79#85"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ~/.julia/juliaup/julia-1.11.5+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:497
Some type information was truncated. Use `show(err)` to see complete types.

```

**Comment by junder873** [comment]
I am also finding this error, it doesn't actaully seem to prevent the package from running (I think).

**Comment by tecosaur** [comment]
I can reproduce this, but it's rather hard to work out what's going on, given the stacktrace is about the "showing an error caused an error" rather than the error itself 😅

**Comment by tecosaur** [comment]
Ok, I think I've found it: there's some issue with `REPL.respond` that I can't be bothered to figure out, but I've been able to sort out a fix: c0dfb5591a252be3c9ad957a3df5cc4f9579af60.

<details>
<summary>
MWE of `REPL.respond` failing for potential future reference
</summary>

```julia
using REPL
using REPL: LineEdit

const REPL_KEY = '}'
const REPL_NAME = :data_toolkit

struct DataCompletionProvider <: REPL.LineEdit.CompletionProvider end

REPL.complete_line(::DataCompletionProvider, state::REPL.LineEdit.PromptState; hint::Bool = false) =
    (String[], "", false)

function init_repl(repl::REPL.AbstractREPL)
    # With *heavy* inspiration from <https://github.com/MasonProtter/ReplMaker.jl>
    # and Pkg.jl.
    main_mode = repl.interface.modes[1] # Julia mode
    data_mode = create_data_mode(repl, main_mode)
    push!(repl.interface.modes, data_mode)
    function key_action(state, args...)
        if isempty(state) || position(LineEdit.buffer(state)) == 0
            buf = copy(LineEdit.buffer(state))
            LineEdit.transition(state, data_mode) do
                LineEdit.state(state, data_mode).input_buffer = buf
            end
        else
            LineEdit.edit_insert(state, REPL_KEY)
        end
    end
    data_keymap = Dict{Any, Any}(REPL_KEY => key_action)
    main_mode.keymap_dict =
        LineEdit.keymap_merge(main_mode.keymap_dict, data_keymap)
    nothing
end

function create_data_mode(repl::REPL.AbstractREPL, base_mode::LineEdit.Prompt)
    data_mode = LineEdit.Prompt("data> ";
        prompt_prefix = "",
        prompt_suffix = "",
        complete = DataCompletionProvider(),
        sticky = true)

    data_mode.repl = repl
    history_provider = base_mode.hist
    history_provider.mode_mapping[REPL_NAME] = data_mode
    data_mode.hist = history_provider

    main_keymap = REPL.mode_keymap(base_mode)
    _, search_keymap = LineEdit.setup_search_keymap(history_provider)
    _, prefix_keymap = LineEdit.setup_prefix_keymap(history_provider, data_mode)

    data_mode.on_done =
        REPL.respond(line -> println("input: ", line), repl, data_mode)

    data_mode.keymap_dict = LineEdit.keymap(Dict{Any, Any}[
        search_keymap,
        main_keymap,
        prefix_keymap,
        LineEdit.history_keymap,
        LineEdit.default_keymap,
        LineEdit.escape_defaults
    ])

    data_mode
end
```
</details>

**Comment by ggebbie** [comment]
thanks a lot!  funny question: can I test this by adding from source?

```julia
(datatoolkit_tutorial) pkg> add https://github.com/tecosaur/DataToolkit.jl
    Updating git-repo `https://github.com/tecosaur/DataToolkit.jl`
ERROR: could not find project file (Project.toml or JuliaProject.toml) in package at `https://github.com/tecosaur/DataToolkit.jl` maybe `subdir` needs to be specified
```

**Comment by tecosaur** [comment]
Ah, that would work except for the fact that the structure of the package repo is changing between 0.9 (released) and 0.10 (in development). You can use something like this, though:

```toml
[deps]
DataToolkit = "dc83c90b-d41d-4e55-bdb7-0fc919659999"
DataToolkitBase = "e209d0c3-e863-446f-9b45-de6ca9730756"
DataToolkitCommon = "9e6fccbf-6142-406a-aa4c-75c1ae647f53"
DataToolkitCore = "caac3e55-418c-402e-a061-64d454aa8f4f"
DataToolkitREPL = "c58528a0-97a2-40a0-9a44-056fe1196995"
DataToolkitStore = "082ec3c2-3fb3-458f-ad22-5e5e31d4377a"

[sources]
DataToolkit = {url = "https:// github.com/tecosaur/DataToolkit.jl.git", subdir="Main"}
DataToolkitBase = {url = "https:// github.com/tecosaur/DataToolkit.jl.git", subdir="Base"}
DataToolkitCommon = {url = "https:// github.com/tecosaur/DataToolkit.jl.git", subdir="Common"}
DataToolkitCore = {url = "https:// github.com/tecosaur/DataToolkit.jl.git", subdir="Core"}
DataToolkitREPL = {url = "https:// github.com/tecosaur/DataToolkit.jl.git", subdir="REPL"}
DataToolkitStore = {url = "https:// github.com/tecosaur/DataToolkit.jl.git", subdir="Store"}
```
