### ISSUE TITLE
More generic SQL Loader

### ISSUE THREAD

**Issue by junder873** [tecosaur/DataToolkit.jl#62]
I was thinking about adding a loader for a more generic SQL setup but I am not sure how it would work. In particular, how would passwords/access to specific databases work?

Currently, looking at the SQLite extension for this package, it opens up a new connection to the database each time it is called. That does not seem possible if the user needs to add a password or connect to a specific type of database.

I could use the raw loader and setup a function to make use of it, so something like:
```toml
[[my_table]]
...
    [[my_table.storage]]
        driver = "raw"
        value = { table = "data.table", columns = ["cols1", "cols2", "cols3"], filter = "col1 > 0" }
    
    [[my_table.loader]]
        driver = "passthrough"
        cache = false
```

And then write a corresponding function in Julia to match:
```julia
function load_sql(db, table, columns, filter=nothing)
    sql = "SELECT $(join(columns, ", ")) FROM $table"
    if filter !== nothing
        sql *= " WHERE $filter"
    end
    return DBInterface.execute(db, sql) |> DataFrame
end
function load_sql(db, tab)
    load_sql(db, tab["table"], tab["columns"], tab["filter"])
end
db = DBInterface.connect(...)
load_sql(db, d"my_data")
```

Some things that seem inconvenient to me about this method:
- There is only one "value" option, so the user is forced to make that into a dictionary
    - That dictionary also all needs to be on one line, reducing legibility, especially if the filters/columns are long
- It is up to the user to implement the necessary functions
- The table cannot be used by other tables in the stack (for example, if I wanted to define "my_combined_table" that merges "my_table" and some other table, this would have to be done in the normal Julia code)

Am I understanding all of that right? Is there a better way to do this that I am not thinking about?
