### ISSUE TITLE
Data collection stack is empty

### ISSUE THREAD

**Issue by arnold-c** [tecosaur/DataToolkit.jl#63]
I seem to be running into the same issue as #61 (stack error) that (I believe) is having knock-on effects on data loading as well. In a fresh session (without an existing Data.toml) I can `init`, add, and then load a file, sometimes. However, it does not consistently work, and importantly, when restarting the julia session, DataToolkit does not detect the data collection and no files can be loaded.

I am using the following Project.toml settings

```toml
[deps]
DataToolkit = "dc83c90b-d41d-4e55-bdb7-0fc919659999"
DataToolkitBase = "e209d0c3-e863-446f-9b45-de6ca9730756"
DataToolkitCommon = "9e6fccbf-6142-406a-aa4c-75c1ae647f53"
DataToolkitCore = "caac3e55-418c-402e-a061-64d454aa8f4f"
DataToolkitREPL = "c58528a0-97a2-40a0-9a44-056fe1196995"
DataToolkitStore = "082ec3c2-3fb3-458f-ad22-5e5e31d4377a"

[sources]
DataToolkit = {url = "https://github.com/tecosaur/DataToolkit.jl.git", subdir="Main"}
DataToolkitBase = {url = "https://github.com/tecosaur/DataToolkit.jl.git", subdir="Base"}
DataToolkitCommon = {url = "https://github.com/tecosaur/DataToolkit.jl.git", subdir="Common"}
DataToolkitCore = {url = "https://github.com/tecosaur/DataToolkit.jl.git", subdir="Core"}
DataToolkitREPL = {url = "https://github.com/tecosaur/DataToolkit.jl.git", subdir="REPL"}
DataToolkitStore = {url = "https://github.com/tecosaur/DataToolkit.jl.git", subdir="Store"}
```

```julia
(myproject) pkg> st -m DataToolkit DataToolkitCore DataToolkitCommon DataToolkitBase DataToolkitREPL DataToolkitStore
Project IndiaFMD v1.0.0-DEV
Status `~/Documents/Repos/myproject/Manifest.toml`
  [dc83c90b] DataToolkit v0.9.0 `https://github.com/tecosaur/DataToolkit.jl.git:Main#`
  [e209d0c3] DataToolkitBase v0.9.1 `https://github.com/tecosaur/DataToolkit.jl.git:Base#`
  [9e6fccbf] DataToolkitCommon v0.9.0 `https://github.com/tecosaur/DataToolkit.jl.git:Common#`
  [caac3e55] DataToolkitCore v0.10.0 `https://github.com/tecosaur/DataToolkit.jl.git:Core#`
  [c58528a0] DataToolkitREPL v0.10.0 `https://github.com/tecosaur/DataToolkit.jl.git:REPL#`
  [082ec3c2] DataToolkitStore v0.10.0 `https://github.com/tecosaur/DataToolkit.jl.git:Store#`
```
